spring:
  mongodb:
    uri: "${MONGODB_URI:mongodb://localhost:27017}"
  data:
    redis:
      url: "${REDIS_URL:redis://localhost:6379}"

copomex:
  api:
    token: ${COPOMEX_TOKEN:pruebas}

logging:
  level:
    com.liverpool: DEBUG
    org.springframework.data.mongodb: DEBUG
