spring:
  mongodb:
    uri: ${MONGODB_URI}

copomex:
  api:
    token: ${COPOMEX_TOKEN}

openapi:
  server-url: https://app.app-escom.org

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

logging:
  level:
    root: WARN
    com.liverpool: INFO
